In [88]:
import numpy as np
from scipy.optimize import linprog

#Given Input/Output Data
I = np.array([[150,70,5],
            [60,20,3],
            [800,140,20],
            [30,15,1]])

O = np.array([[15,225],
            [5.4,70],
            [56,1300],
            [2.1,40]])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
#Assign Each Variables

m,n1=I.shape
m2,n2=O.shape
f=np.concatenate((I,np.zeros((m2,n2))),axis=1)
lb=np.array([0]*(n1+n2))
lb
A=np.concatenate((np.zeros((m,n1)),O),axis=1)-np.concatenate((I,np.zeros((m2,n2))),axis=1)
b=np.zeros(m)
f=np.concatenate((I,np.zeros((m,n2))),axis=1)


In [109]:
x = []
#Use for-loop to calculate linear programming
for i in range(0,m):
    Aeq=np.array([np.concatenate((np.zeros(n1),O[i,:]),axis=0)])
    beq=np.array([1])
    z=linprog(f[i,:], A_ub=A, b_ub=b,A_eq=Aeq, b_eq=beq, options={"disp": True})
    x.append(z.x)

x=array(x)
print (x)    
result=x*np.concatenate((I,O),axis=1)  
print (result[:,0]+result[:,1]+result[:,2])


Optimization terminated successfully.
         Current function value: 1.000000    
         Iterations: 3
Optimization terminated successfully.
         Current function value: 1.000000    
         Iterations: 4
Optimization terminated successfully.
         Current function value: 1.000000    
         Iterations: 3
Optimization terminated successfully.
         Current function value: 1.179487    
         Iterations: 3
[[0.00666667 0.         0.         0.01449275 0.00347826]
 [0.01123844 0.01628468 0.         0.16485726 0.00156815]
 [0.00125    0.         0.         0.00271739 0.00065217]
 [0.03931624 0.         0.         0.08547009 0.02051282]]


     fun: 1.1794871794871797
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([0.        , 0.46153846, 0.        , 0.17948718])
  status: 0
 success: True
       x: array([0.03931624, 0.        , 0.        , 0.08547009, 0.02051282])

In [124]:
result=x*np.concatenate((I,O),axis=1)  
#print (result[:,0]+result[:,1]+result[:,2])
result

array([[1.        , 0.        , 0.        , 0.2173913 , 0.7826087 ],
       [0.67430639, 0.32569361, 0.        , 0.89022919, 0.10977081],
       [1.        , 0.        , 0.        , 0.15217391, 0.84782609],
       [1.17948718, 0.        , 0.        , 0.17948718, 0.82051282]])