In [2]:
import tensorflow as tf

# Constants
s = tf.constant(2, name='scalar') 
m = tf.constant([[1, 2], [3, 4]], name='matrix') 
with tf.Session() as sess:
    print(sess.run(s)) 
    print(sess.run(m))


2
[[1 2]
 [3 4]]


In [5]:
# Varibles
a = tf.ones((2,2)) 
b = tf.Variable(tf.zeros((2,2))) 
with tf.Session() as sess: 
    print(sess.run(a)) 
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [7]:
# Placeholders
node1 = tf.placeholder(tf.float32) 
node2 = tf.placeholder(tf.float32) 
node3 = tf.add(node1,node2) 
tf.Session().run(node3, feed_dict={node1 : 2, node2 : 3})


5.0

In [6]:
# Operations: tf.add
a = tf.constant(1) 
b = tf.constant(2) 
c = tf.add(a, b) 
with tf.Session() as sess:
    print(sess.run(c)) 


3


In [8]:
# Operations: tf.subtract
a = tf.constant(1) 
b = tf.constant(2) 
c = tf.subtract(a, b) 
with tf.Session() as sess:
    print(sess.run(c)) 


-1


In [9]:
# Matrix Multiplication
# 2-D tensor `a` 
# [[1, 2, 3], 
# [4, 5, 6]] 
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) 
# 2-D tensor `b` 
# [[ 7, 8], 
# [ 9, 10], 
# [11, 12]] 
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2]) 
# `a` * `b` 
# [[ 58, 64], 
# [139, 154]] 
c = tf.matmul(a, b) 
with tf.Session() as sess: 
    print(sess.run(c)) 

[[ 58  64]
 [139 154]]


In [10]:
# Condition
t1 = tf.constant(1) 
t2 = tf.constant(2) 

def f1(): return t1+t2 
def f2(): return t1-t2 

res = tf.cond(tf.less(t1, t2), f1, f2) 
with tf.Session() as sess: 
    print(sess.run(res))


3


In [11]:
# While loop
def cond(t1, t2): return tf.less(t1, t2) 
def body(t1, t2): return [tf.add(t1, 1), t2] 

t1 = tf.constant(1) 
t2 = tf.constant(5) 

res = tf.while_loop(cond, body, [t1, t2]) 

with tf.Session() as sess: 
    print(sess.run(res)) 


[5, 5]


In [12]:
# Where does code run
with tf.device("/cpu:0"): 
    a = tf.constant(1) 
    b = tf.constant(2) 
    c = tf.subtract(a, b) 
    with tf.Session() as sess: 
        print(sess.run(c)) 


-1
